GET http://localhost:3001/

###

GET http://localhost:3001/recursive

###

POST http://localhost:3001/recover

###

POST http://localhost:3001/purge

###

GET http://localhost:3001/download?download=ipsum.png

###

GET http://localhost:3001/test
